name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22.6

    - name: Check out code
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go mod download

    - name: Vet
      run: make vet

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest

    - name: Test
      run: make test